1st order cky implementation
harvardnlp/pytorch-struct pull request #83
Opened 2020-12-05 20:47 UTC by teffland

Hi,

I'd like to contribute this implementation of a first-order cky-style crf with anchored rule potentials: $\phi[i,j,k,A,B,C] := \phi(A_{i,j} \rightarrow B_{i,k}, C{k+1,j})$.

I also added code to the `_Struct` class that allows calculating marginals even if input tensors don't require a gradient (i.e., after `model.eval()`)

Please let me know if you'd like to see any changes.

Thanks,
Tom

2020-12-07 00:04 UTC, srush requested changes
This looks great! Very excited to add. 

Couple questions: 

* Reshape always worries me. Can those be views? 
* Repeat is almost never necessary. What operators is failing there? 
* I would prefer the sr.sum be replace with a view and then a single sum. 

Were you able to run any tests? I know travis is broken (I need to move to github), but it would be great to have at least one test. For other algorithms I enumerate all examples and score. Can you try that?

2020-12-07 14:28 UTC, teffland commented
Great, excited to contribute!

Re: your questions

* Reshape: I can definitely try this with view. Just curious, why does reshape worry you? I thought reshape was just a more robust version of view that creates a contiguous copy in cases where view would fail. 
* Repeat: true, I can try without and it should work I think, I guess I just naturally tend towards implementations that go through all of the steps explicitly but I should get better about trusting broadcasting.
* One sum: this is definitely doable, will make that change
* I did write some tests locally in a notebook a while back. I can dig those up and incorporate them. By enumerate and score, you mean check that the dp partition matches the partition computed by explicitly enumerating all structures, correct?

Thanks for the feedback,
Tom

2020-12-07 14:39 UTC, srush commented
I can help with testing. Yes, all the algorithms in torch struct test that the enumeration has the same marginals. Its helped catch a ton of bugs. 

* Reshape- maybe they changed this, earlier version caused problems.

2020-12-07 16:13 UTC, teffland commented
Cool, help with the testing would nice but I can also take a crack at it later. When I get to it I'll also incorporate the suggested changes, (and will try it out with view).

2021-01-11 03:06 UTC, srush commented
Hey sorry, I flaked on helping out here. Send me an email if you want to work on it more. I'm going to do some repo maintenance this week.

2021-01-13 14:19 UTC, teffland commented
Hey, no worries same here. Will send an email

2021-01-20 17:16 UTC, teffland commented
included in https://github.com/harvardnlp/pytorch-struct/pull/93

2021-01-20 18:49 UTC, srush commented
(still not merged, keeping open)

2021-01-20 18:49 UTC, closed without merging